ole-app/olefs/src/main/resources/org/kuali/ole/deliver/datadictionary/OleDeliverRequestSearch.xml

OLE-7510 : Changed the Button Label from "Save" to "Submit" in the Request Screen.

OLE-7510 : Changed the Button Label from "Save" to "Submit" in the Request Screen.

---

ole-app/olefs/src/main/java/org/kuali/ole/OLEConstants.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/batch/OleNoticeBo.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkin/CheckinBaseController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkin/CheckinUIController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkin/MissingPieceNoteHandler.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/notice/executors/LoanNoticesExecutor.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/notice/executors/MissingPieceNoticesExecutor.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/notice/valuesFinder/OleNoticeFieldLabelMappingKeyValuesFinder.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/notice/valuesFinder/OleNoticeItemFieldLabelMappingKeyValuesFinder.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/notice/valuesFinder/OleNoticeTypeKeyValuesFinder.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/service/MissingPieceEmailContentFormatter.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/service/NoticeMailContentFormatter.java
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/service/itemInfo.ftl
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/service/notice.ftl
ole-app/olefs/src/test/java/org/kuali/ole/deliver/service/NoticeMailContentFormatterTest.java

Added MissingPiece Notice functionality and included MissingPiece note to email notice patron receives. jira OLE-6416.

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkin/CheckinBaseController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/notice/executors/OnHoldNoticesExecutor.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/util/printSlip/OnHoldRecieptPrintSlipUtil.java
ole-app/olefs/src/main/java/org/kuali/ole/service/OLEEResourceHelperService.java

OLE-8245 : Made the access activation workflow status to be updated appropriately at the last step.

OLE-8245 : Made the access activation workflow status to be updated appropriately at the last step.

---

ole-app/olefs/src/main/java/org/kuali/ole/describe/controller/EditorController.java
ole-app/olefs/src/main/java/org/kuali/ole/describe/controller/WorkEInstanceOlemlEditor.java
ole-app/olefs/src/main/resources/org/kuali/ole/OleApplicationResources.properties
ole-app/olefs/src/main/resources/org/kuali/ole/describe/view/WorkEInstanceOlemlView.xml
ole-app/olefs/src/main/resources/org/kuali/ole/describe/view/WorkOleItemsPage.xml
ole-app/olefs/src/main/webapp/ole/describe/scripts/editor.js
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsHoldingsDocumentManager.java

OLE-7404 & OLE-6170 : Populated Donor Public Display & Donor Note while Selecting Donor Code & validated donor code.

OLE-7404 & OLE-6170 : Populated Donor Public Display & Donor Note while Selecting Donor Code & validated donor code.

---

ole-app/olefs/src/main/java/org/kuali/ole/OLEConstants.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/web/struts/OleRequisitionAction.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/document/authorization/AccountingLineAuthorizerBase.java
ole-app/olefs/src/main/java/org/kuali/rice/kew/engine/BlanketApproveEngine.java
ole-app/olefs/src/main/webapp/WEB-INF/tags/module/select/oleitems.tag
ole-app/olefs/src/main/webapp/WEB-INF/tags/portal/channel/oleSelectAcquire/oleReports.tag

OLE-6843 USD calculation for foreign currency

OLE-6843 USD calculation for foreign currency

---

ole-app/olefs/src/main/java/org/kuali/ole/select/controller/OLEInvoiceController.java

OLE-8372 : Merged the code from 1.6.2 code base to 2.1 code base.

OLE-8372 : Merged the code from 1.6.2 code base to 2.1 code base.

---

ole-app/olefs/src/main/java/org/kuali/ole/select/controller/OLEInvoiceController.java

OLE-8372 : Merged the code from 1.6.2 code base to 2.0 code base.

OLE-8372 : Merged the code from 1.6.2 code base to 2.0 code base.

---

ole-app/olefs/src/main/resources/org/kuali/ole/describe/view/WorkEInstanceOlemlView.xml

OLE-8299 - Relocating view of Access Information tab

OLE-8299 - Relocating view of Access Information tab

---

ole-app/olefs/src/main/resources/org/kuali/ole/describe/view/WorkEInstanceOlemlView.xml

OLE-8299 - Relocating AccessInfoSection

OLE-8299 - Relocating AccessInfoSection

---

ole-app/olefs/src/main/java/org/kuali/ole/select/OleSelectConstant.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/OleVendorCreditMemoDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/OleCreditMemoService.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/impl/OleCreditMemoServiceImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/web/struts/OleVendorCreditMemoAction.java
ole-app/olefs/src/main/resources/org/kuali/ole/OleApplicationResources.properties

OLE-7117 Credit Memo against a Vendor Fails

OLE-7117 Credit Memo against a Vendor Fails

---

ole-app/olefs/src/main/java/org/kuali/ole/select/controller/OLEInvoiceController.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/impl/OleInvoiceServiceImpl.java

OLE-8027 Prorated Additional Charges Associated with First PO on Invoice

OLE-8027 Prorated Additional Charges Associated with First PO on Invoice

---

ole-app/olefs/src/main/java/org/kuali/ole/select/OleSelectConstant.java
ole-app/olefs/src/main/java/org/kuali/ole/select/batch/service/RequisitionCreateDocumentService.java
ole-app/olefs/src/main/java/org/kuali/ole/select/batch/service/impl/RequisitionCreateDocumentServiceImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/select/controller/OLEEResourceRecordController.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/OleRequisitionDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/OleVendorCreditMemoDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/OleCreditMemoService.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/impl/OleCopyHelperServiceImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/impl/OleCreditMemoServiceImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/web/struts/OleVendorCreditMemoAction.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/OLEConstants.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/document/authorization/AccountingLineAuthorizerBase.java
ole-app/olefs/src/main/resources/org/kuali/ole/OleApplicationResources.properties
ole-app/olefs/src/main/webapp/WEB-INF/tags/module/select/oleitems.tag

OLE-8236 Added system parameter value to requisition document while creating through eResource.

Ole 8236 2.1

---

ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/service/OlePurapService.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/service/impl/OlePurapServiceImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/OlePurchaseOrderDocument.java

OLE-8471 : POs attached to e-resource record do not display invoice history

OLE-8471 : POs attached to e-resource record do not display invoice history

---

ole-app/olefs/src/main/java/org/kuali/ole/OLEConstants.java
ole-app/olefs/src/main/java/org/kuali/rice/kew/engine/BlanketApproveEngine.java

OLE-7010 Changing Workflow for Invoices

OLE-7010 Changing Workflow for Invoices

---

ole-app/olefs/src/main/java/org/kuali/ole/describe/controller/WorkItemOlemlEditor.java

OLE-6896 : double quotes in donor notes not working

OLE-6896 : double quotes in donor notes not working

---

ole-app/olefs/src/main/java/org/kuali/ole/sys/OLEConstants.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/batch/service/impl/BatchFileAdminAuthorizationServiceImpl.java

OLE-3904 - Made Bibimport report file downloadable

OLE-3904 - Made Bibimport report file downloadable

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/lookup/OleDeliverRequestLookupableImpl.java

Override the MessageMapInfo to provide correct message and removed the conflicting one. Jira OLE-7445

---

ole-app/olefs/src/main/java/org/kuali/ole/service/impl/OLEEResourceSearchServiceImpl.java
ole-app/olefs/src/main/webapp/WEB-INF/ftl/eResource-Holdings-list.ftl
ole-app/olefs/src/main/webapp/ole/eresource/scripts/eresource.js

OLE-8298 : Populated the url field in the E-Holdings tab under EResource.

OLE-8298 : Populated the url field in the E-Holdings tab under EResource.

---

ole-app/olefs/src/main/java/org/kuali/ole/sys/batch/service/impl/BatchFileAdminAuthorizationServiceImpl.java

OLE-3904 - Made Bibimport report file downloadable, included other file pattern related to Bibimport

OLE-3904 - Made Bibimport report file downloadable, included other file pattern related to Bibimport

---

ole-common/ole-docstore-common/src/main/java/org/kuali/ole/docstore/common/document/EHoldings.java

e-holdings status not identified in batch process

OLE-7981 	

---

ole-app/olefs/src/main/java/org/kuali/ole/batch/ingest/BatchProcessInvoiceIngest.java

Enhancements to Load Reports for Batch Bib/Instance/Item import

OLE-3904  

---

ole-app/olefs/src/main/webapp/ole/describe/scripts/editor.js

Better display when deleting a bib

OLE-6516  

---

ole-app/olefs/src/main/java/org/kuali/ole/select/document/OleReceivingQueueSearchDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/impl/ReceivingQueueDAOServiceimpl.java
ole-app/olefs/src/main/webapp/WEB-INF/jsp/OleReceivingQueueSearch.jsp

OLE-7660 - Fixed multiple PO search,link issue

OLE-7660 - Fixed multiple PO search,link issue

---

ole-app/olefs/src/main/java/org/kuali/ole/alert/controller/OleTransactionalDocumentControllerBase.java
ole-app/olefs/src/main/java/org/kuali/ole/select/controller/OLEEResourceRecordController.java
ole-app/olefs/src/main/java/org/kuali/ole/service/OLEEResourceHelperService.java
ole-app/olefs/src/main/java/org/kuali/ole/service/impl/OLEEResourceSearchServiceImpl.java
ole-app/olefs/src/main/resources/org/kuali/ole/select/view/OLEEResourceMainTab.xml
ole-app/olefs/src/main/resources/org/kuali/ole/select/view/OLEEResourceView.xml
ole-app/olefs/src/main/resources/org/kuali/ole/select/view/dialog/eresource-delete-confirmation.xml

OLE-8440 : Added a confirmation dialog while deleting an EResource Record.

OLE-8440 : Added a confirmation dialog while deleting an EResource Record.

---

ole-app/olefs/src/main/java/org/kuali/ole/vnd/businessobject/VendorDetail.java
ole-app/olefs/src/main/java/org/kuali/ole/vnd/document/VendorMaintainableImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/vnd/document/validation/impl/OleVendorRule.java

OLE-8306:added logic to save vendor contact phone number informations.

OLE-8306:added logic to save vendor contact phone number informations.

---

ole-app/olefs/src/main/java/org/kuali/ole/batch/impl/ExportDataServiceImpl.java

bound with bib details are coming made it to be in order.

OLE-8163  

---

ole-app/olefs/src/main/java/org/kuali/ole/describe/controller/OLESearchController.java

Search Workbench not displaying records, even when indicating found

  OLE-8466 -

---

ole-app/olefs/src/main/webapp/WEB-INF/tags/module/select/oleitems.tag

OLE-7590 PO Amendment Editable Fields

OLE-7590 PO Amendment Editable Fields

---

ole-app/olefs/src/main/java/org/kuali/ole/vnd/businessobject/VendorDetail.java
ole-app/olefs/src/main/java/org/kuali/ole/vnd/document/VendorMaintainableImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/vnd/document/validation/impl/OleVendorRule.java

OLE-8306:Merged the code from 2.0 code base to 2.1 code base.

OLE-8306:Merged the code from 2.0 code base to 2.1 code base.

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/bo/OleLoanDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/OlePatronLoanNoticesSentController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/form/OlePatronLoanNoticesSentForm.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/maintenance/OlePatronMaintenanceImpl.java
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/datadictionary/OlePatronDocument.xml
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/document/OlePatronDocumentMaintenanceDocument.xml
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/service/notice.ftl
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/OlePatronLoanNoticesSentView.xml
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/OlePatronLoanedRecordView.xml

Modified for jira OLE-7743. Changes for re-sending  already sent notice to the patron through the patron screen

---

ole-app/olefs/src/main/java/org/kuali/ole/batch/impl/BatchProcessDeleteServiceImpl.java

- Batch delete fails to delete once files are over a certain ize

OLE-7295 	

---

ole-app/olefs/src/main/resources/org/kuali/ole/select/view/OLEPlatformMainTab.xml

OLE-8024 : Made the Platform vendor field editable even after a vendor is selected.

OLE-8024 : Made the Platform vendor field editable even after a vendor is selected.

---

ole-app/olefs/src/main/java/org/kuali/ole/describe/controller/OLESearchController.java

- Stack trace error on SearchWorkbench - when no result  found

    OLE-8545 

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/OlePatronMaintenanceDocumentController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/util/DeliverRequestUtil.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/util/ItemInfoUtil.java

Jira OLE-8508 : Added logic to handle the requests while changes in patron barcode.

Jira OLE-8508 : Added logic to handle the requests while changes in patron barcode.

---

ole-app/olefs/src/it/resources/org/kuali/ole/workflows/092_select/OleEResourceDocType.xml
ole-app/olefs/src/main/java/org/kuali/ole/OLEConstants.java
ole-app/olefs/src/main/java/org/kuali/ole/select/rule/OLEAccessActivationConfigurationRule.java
ole-app/olefs/src/main/resources/org/kuali/ole/select/document/datadictionary/OLEAccessActivationConfigurationMaintenanceDocument.xml
ole-app/olefs/src/main/resources/org/kuali/ole/workflows/092_select/OleEResourceDocType.xml
ole-app/olefs/src/main/resources/org/kuali/rice/krad/ApplicationResources.properties

OLE-8245 : Fixed the issues occurred in Access Activation Configuration screen while doing Blanket Approve.

OLE-8245 : Fixed the issues occurred in Access Activation Configuration screen while doing Blanket Approve.

---

ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsBibDocumentManager.java

OLE-8550 	

---

ole-app/olefs/src/main/webapp/ole/deliver/loan/script/circ.js

OLE-8228 : Added the Loan screen search box for Checked out Item List.

OLE-8228 : Added the Loan screen search box for Checked out Item List.

---

ole-app/olefs/src/main/java/org/kuali/ole/select/document/validation/impl/OleValidationRuleBase.java

OLE-7931 : Code modified to fix issue in edit copies in POA.

OLE-7931 : Related to OLE-4799 - Unable to edit copies (quantity) in POA

---

.gitignore

Eclipse produces folders that are not relevant to the project, these should be ignored.

Add Eclipse specific files / folders to .gitignore

---

ole-app/olefs/src/main/resources/org/kuali/ole/deliver/datadictionary/OLEDeliverItemSearchView.xml
ole-app/olefs/src/main/resources/org/kuali/ole/describe/view/WorkOleItemsPage.xml

OLE-7791 : Changed the miss-labeled data field in the Return History.

OLE-7791 : Changed the miss-labeled data field in the Return History.

---

ole-common/ole-docstore-common/src/main/java/org/kuali/ole/docstore/common/util/CallNumberUtil.java
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/dao/CallNumberMigrationDao.java
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/dao/HoldingsCallNumberProcessor.java
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/dao/ItemCallNumberProcessor.java

OLE-8518 	

---

ole-app/olefs/src/it/resources/org/kuali/ole/deliver/rules/chicago/checkin/on-hold-check.drl
ole-app/olefs/src/it/resources/org/kuali/ole/deliver/rules/demo/checkin/on-hold-check.drl
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkin/CheckinBaseController.java
ole-app/olefs/src/main/resources/org/kuali/ole/rules/demo/checkin/on-hold-check.drl

OLE-8187 : Enabled the automatic checkout process for the unstaffed circulation desk.

OLE-8187 : Enabled the automatic checkout process for the unstaffed circulation desk.

---

ole-app/olefs/src/main/java/org/kuali/ole/describe/controller/WorkItemOlemlEditor.java

Parameter to set call number type default on the Item record. When we click H in Editor

    OLE-8274 -

---

ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/circulations/dialogs/checkin-note-dialog.xml

OLE-8587 : Changed the Uif-MessageField to Uif-DataField in the checkin-note-dialog.xml.

OLE-8587 : Changed the Uif-MessageField to Uif-DataField in the checkin-note-dialog.xml.

---

ole-app/olefs/src/main/java/org/kuali/ole/select/document/service/impl/ReceivingQueueDAOServiceimpl.java

OLE-8581 - Fixed the claiming checkbox issue in Receiving and Claiming Queue Search screen

OLE-8581 - Fixed the claiming checkbox issue in Receiving and Claiming Queue Search screen

---

ole-app/olefs/src/it/java/org/kuali/ole/deliver/ItemBarcode_IT.java
ole-app/olefs/src/it/java/org/kuali/ole/deliver/PatronBarcode_IT.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/ItemBarcodeUpdateHandler.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/PatronBarcodeUpdateHandler.java

Jira OLE-8508 : Added testcases and Handler for updating patron and item barcode.

Jira OLE-8508 : Added testcases and Handler for updating patron and item barcode.

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/OlePatronMaintenanceDocumentController.java

Jira OLE-8508 : Patron barcode updation using handler class.

Jira OLE-8508 : Patron barcode updation using handler class.

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/PatronLookupCircBaseController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkin/DamagedItemNoteHandler.java

OLE-8583 : Removed the expired proxy patrons from the patron's proxy list.

OLE-8583 : Removed the expired proxy patrons from the patron's proxy list.

---

ole-app/olefs/src/it/java/org/kuali/ole/deliver/ItemBarcode_IT.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/ItemBarcodeUpdateHandler.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkout/CircUtilController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/rest/OleDsDataUpdateRestController.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/util/ItemInfoUtil.java
ole-common/ole-utility/src/main/java/org/kuali/ole/audit/OleAuditManager.java
ole-common/ole-utility/src/main/java/org/kuali/ole/utility/OleHttpRestClient.java
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsHoldingsDocumentManager.java
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsItemDocumentManager.java

Jira OLE-8457 : Item barcode updation using handler class

Jira OLE-8457 : Item barcode updation using handler class

---

ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsHoldingsDocumentManager.java
ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsItemDocumentManager.java

Jira OLE-8457 : Removed unwanted lines

Jira OLE-8457 : Removed unwanted lines

---

ole-app/olefs/src/it/resources/org/kuali/ole/deliver/rules/demo/checkout/2-H.drl
ole-app/olefs/src/main/resources/org/kuali/ole/rules/demo/checkout/2-H.drl

OLE-8602 : Added the rule file for 2-Hour loan in the demo rules.

OLE-8602 : Added the rule file for 2-Hour loan in the demo rules.

---

ole-docstore/ole-docstore-engine/src/main/java/org/kuali/ole/docstore/engine/service/storage/rdbms/RdbmsItemDocumentManager.java

Jira OLE-8457 : Added null check condition.

Jira OLE-8457 : Added null check condition.

---

ole-app/olefs/src/it/resources/org/kuali/ole/deliver/rules/chicago/general_checks/existing-loan-or-requests.drl
ole-app/olefs/src/it/resources/org/kuali/ole/deliver/rules/demo/general/existing-loan-or-requests.drl
ole-app/olefs/src/main/java/org/kuali/ole/deliver/controller/checkout/CheckoutItemController.java
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/circulations/circ-view.xml
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/circulations/dialogs/block-checkin-dialog.xml
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/circulations/dialogs/item-already-loaned-dialog.xml
ole-app/olefs/src/main/resources/org/kuali/ole/rules/demo/general/existing-loan-or-requests.drl

OLE-8114 : Added logic to do background checkin when there is no popup blocks for the item.

OLE-8114 : Added logic to do background checkin when there is no popup blocks for the item.

---

ole-app/olefs/src/main/java/org/kuali/ole/describe/krad/ExistingLoanSearchLayout.java
ole-app/olefs/src/main/webapp/WEB-INF/ftl/existing-loan-list.ftl
ole-app/olefs/src/main/webapp/ole/deliver/loan/script/circ.js

Drools: Loan screen columns are sort-able in all items currently checked out list  for 2.0

OLE-8227 	 

---

ole-app/olefs/src/main/java/org/kuali/ole/module/purap/businessobject/AbstractRelatedView.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/businessobject/AccountsPayableItemBase.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/businessobject/InvoiceView.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/businessobject/PaymentRequestView.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/businessobject/PurApAccountingLineBase.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/businessobject/PurchasingCapitalAssetItemBase.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/AccountsPayableDocumentBase.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/PurchasingAccountsPayableDocumentBase.java
ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/PurchasingDocumentBase.java
ole-app/olefs/src/main/java/org/kuali/ole/select/businessobject/OleInvoiceItem.java
ole-app/olefs/src/main/java/org/kuali/ole/select/businessobject/OlePurchaseOrderItem.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/OleInvoiceDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/select/document/OlePaymentRequestDocument.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/businessobject/AccountingLineBase.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/document/LedgerPostingDocumentBase.java
ole-app/olefs/src/main/resources/org/kuali/ole/select/ojb-select.xml

OLE-8567 - Removed ERROR and WARN messages while executing autoClosePurchaseOrdersJob

OLE-8567 - Removed ERROR and WARN messages while executing autoClosePurchaseOrdersJob

---

ole-app/olefs/src/main/webapp/ole/receive/scripts/serialSearch.js

OLE-8416 - Fixed the click issue on Show link of SRR

OLE-8416 - Fixed the click issue on Show link of SRR

---

ole-app/olefs/src/main/webapp/WEB-INF/tags/portal/channel/oleDeliver/olePatron.tag

OLE-8398 - Added the space between the links in Deliver  tab

OLE-8398 - Added the space between the links in Deliver  tab

---

ole-app/olefs/src/main/java/org/kuali/ole/deliver/bo/FeeType.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/bo/ItemBillHelperService.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/bo/PatronBillHelperService.java
ole-app/olefs/src/main/java/org/kuali/ole/deliver/bo/PatronBillMaintenanceDocumentController.java
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/BillView.xml
ole-app/olefs/src/main/resources/org/kuali/ole/deliver/view/ItemBillView.xml

OLE-8669 - Separated the single field Item Chronology Own Location into two fields Item Chronology and Item Own Location

OLE-8669 - Separated the single field Item Chronology Own Location into two fields Item Chronology and Item Own Location

---

ole-app/olefs/src/main/java/org/kuali/ole/module/purap/document/service/impl/OlePurapServiceImpl.java
ole-app/olefs/src/main/java/org/kuali/ole/sys/OLEConstants.java

Ole-8662 Not able to close PO in TST in 2.1

Ole-8662 Not able to close PO in TST in 2.1
